services:
  my-service:
    image: ${DOCKER_IMAGE_URI}
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Or specify particular GPUs, e.g., "0,1"
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # If additional capabilities are needed
